# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d57f6a6145e7088452759fc177be58a561635d1ffc4814ee18ed1e8857502a72cc3c8531271026424f34c60310ce793c50def7b98dd7de50cf7de190f5591db

test:
  secret_key_base: 7fbc8377cfa58eae8302a2096788391cfbdc92952da80ef3415e70ea5301119a991a230a27f7dd7270deac8e14be0911e62aee67ed3c9ef3b9060424962317f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
